### ISSUE TITLE
ImportError: cannot import name abc

### ISSUE THREAD

**Issue by arielman** [prashant-shahi/ToDo-List-using-Flask-and-MongoDB#8]
I ran the docker up command and got:
flask-app   |   File "/usr/lib/python2.7/site-packages/bson/code.py", line 18, in <module>
flask-app   |     from bson.py3compat import abc, string_type, PY3, text_type
flask-app   | ImportError: cannot import name abc

**Comment by prashant-shahi** [comment]
@arielman phew, this is resolved with latest changes. after 2 years :sweat_smile: 
Thanks for raising the issue.
